# BioJupies

In [1]:
import pandas as pd
import numpy as os
import os

In [45]:
INPUT = 'D:/DDesktop/_work/data/canada/input/'
FEATURECOUNTS = INPUT + 'featureCounts/'
OUTPUT = 'D:/DDesktop/_work/data/canada/output/'

In [46]:
counts = [file for file in os.listdir(FEATURECOUNTS) if 'summary' not in file]

num_files = len(counts)
print('num_files:', num_files)

df_results = pd.DataFrame()

# Get raw HALO 6h files
for file in counts:

    if '_Halo6h' in file:

        # print(file)
        filename = file.split('_')[1]
        # print(filename)

        df = pd.read_csv(FEATURECOUNTS + file, sep = '\t', comment = '#')
        df = df.iloc[:, [0, -1]]
        df.rename(columns = {df.columns[-1] : filename}, inplace = True)
        df_results = pd.concat([df_results, df])
    
    if '_Ve6h' in file:

        filename = file.split('_')[1]
        df = pd.read_csv(FEATURECOUNTS + file, sep = '\t', comment = '#')
        df = df.iloc[:, [0, -1]]
        df.rename(columns = {df.columns[-1] : filename}, inplace = True)
        df_results = pd.concat([df_results, df])


# Melt
df_results = pd.melt(df_results, id_vars = 'Geneid')
# Drop duplicates
df_results = df_results[~df_results['value'].isna()]
df_results.drop_duplicates(subset = ['Geneid', 'variable'], inplace = True)
# Pivot
df_results = pd.pivot(df_results, index = 'Geneid', columns = 'variable', values = 'value')
# Save file
df_results.to_csv(OUTPUT + 'BIOJUPES.csv', index = True)
# Get vehicle control files
df_results.head()

num_files: 192

variable  Halo6h1  Halo6h2  Halo6h3  Ve6h1  Ve6h2  Ve6h3
Geneid
A1BG         23.0     26.0     21.0   23.0   29.0   36.0
A1BG-AS1      2.0      5.0      1.0    7.0    2.0    8.0
A1CF          0.0      1.0      0.0    0.0    1.0    2.0
A2M           4.0      5.0      5.0    2.0    4.0    4.0
A2M-AS1       2.0      5.0      4.0    1.0    1.0    0.0

In [12]:
df_results[(~df_results['Halo6h1'].isna()) &
           (~df_results['Halo6h2'].isna()) &
           (~df_results['Halo6h3'].isna())]

Empty DataFrame
Columns: [Geneid, Halo6h1, Halo6h3, Halo6h2]
Index: []